# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tzbb' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tzbb
 react_native_path = "../node_modules/react-native”  #在podfile所在的目录下找到node_modules文件夹

  pod 'AFNetworking'
#  pod 'RSKImageCropper'
#  pod 'QBImagePickerController'
  pod "React", :path => react_native_path, :subspecs => [
  'Core',
  'ART',
  'RCTActionSheet',
  'RCTAdSupport',
  'RCTGeolocation',
  'RCTImage',
  'RCTNetwork',
  'RCTPushNotification',
  'RCTSettings',
  'RCTText',
  'RCTVibration',
  'RCTWebSocket',
  'RCTLinkingIOS',
  'RCTAnimation',
  'DevSupport',
  'jschelpers_legacy',
  'cxxreact_legacy',
  'BatchedBridge'
  ]
 pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
 pod "workbench",:path=>"../node_modules/tzbb-mc-workbench"
 pod  "RNVectorIcons", :path =>  "../node_modules/react-native-vector-icons"
 pod 'ImageCropPicker',:path=>'../'
 pod "QBImagePickerController", :path =>  "../node_modules/react-native-image-crop-picker/ios/QBImagePicker"
end
